### ISSUE TITLE
PA Review: New account creation, login, and guest/demo login

### ISSUE THREAD

**Issue by milesmcleod** [milesmcleod/purplenote#1]
Link: [Purplenote Heroku](https://purplenote.herokuapp.com)

- [x] User can create an account
- [x] User can successfully log in
- [x] Demo user animation displays and works properly
- [x] All links to signup and login forms are functional
- [x] Responsive design on Splash page is clean and functional

**Comment by milesmcleod** [comment]
I've left getState() on the window, as well as dispatch(). To log out and re-test, you can use dispatch(deleteSession()) in the console. As of now, logging in routes back to '/', so there's no noticeable change when signing in with a demo user from the home page. Once the notes component is built, the sign in will redirect to '/home' instead.

**Comment by AAlfarho** [comment]
Great job! Your splash/login/logout screens look amazing !!  The attention to detail, transitions, color change is incredible! 
Just a couple of things.

+ The links under `By clicking Create Account, I agree to the Terms of Service and Privacy Policy.` They all redirect to the _sign up_, instead of the terms of service and privacy policy.
+ When creating new users or login in with incorrect credentials, the values previously provided are lost, so if the user provided an incorrect password, they'll have to retype their username, let's change that.
+ Add a dummy button for testing your logout functionality.

**Comment by AAlfarho** [comment]
Check the actions (checkbox) once you completed them, so I can have a clearer view of your progress.

**Comment by milesmcleod** [comment]
Fixed those bugs.
Terms of service + Privacy policy are now dummy links.
When logging in with bad credentials, now the form only erases the password input. I also fixed it so session errors do not carry over when moving from login -> signup forms and vice versa.
There is now a logout button in the bottom left corner.

**Comment by AAlfarho** [comment]
Good job catching that bug!
One last thing, whenever displaying a form, in this case, our sign up or sign in, lets set the set focus directly on the username input, that way the user can start typing the moment your form is loaded.

**Comment by milesmcleod** [comment]
i put autofocus on, but when i switch between forms (without refreshing) the autofocus is lost because of the click. should i be worried about that? otherwise it seems all good.
